name: sbpipe
channels:
  - conda-forge
  - bioconda
  - r
  - pkgw
  - defaults
dependencies:
  - colorlog
  - nose
  - pandas
  - pyaml
  - python
  - numpy
  - scipy
  - setuptools
  - r-ggplot2 >=2.2.0
  - r-hmisc
  - r-plyr
  - r-reshape2
  - r-scales
  - texlive-selected
  - xorg-libx11
  - libpng
