# This file is part of sbpipe.
#
# sbpipe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sbpipe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sbpipe.  If not, see <http://www.gnu.org/licenses/>.


# note, texlive can be installed via conda, but still only works for linux/osx machines.

name:
  - sbpipe
channels:
  - pdp10
  - conda-forge
  - fbergmann
  - defaults
dependencies:
  - nose
  - pandas
  - pyyaml
  - python
  - numpy
  - scipy
  - setuptools
  - sbpiper=1.6.*
  - colorlog             # -c conda-forge
  - python-copasi        # -c fbergmann
#  - snakemake           (not available on windows) -c bioconda
#  - texlive-core        (not available on windows) -c pkgw
#  - texlive-selected    (not available on windows) -c pkgw
